#!/usr/bin/env python3
"""
Standalone Test Suite for Caja Context Menu Manager
Tests core logic without GUI dependencies
"""

import unittest
import tempfile
import shutil
import os
import json
from pathlib import Path
import random
import string


class ScriptGenerator:
    """Standalone version of script generation logic"""
    
    @staticmethod
    def generate_script(command, multiple=False, terminal=False):
        """Generate the Caja script"""
        script = "#!/bin/bash\n"
        script += "# Caja script - auto-generated by Caja Context Manager\n\n"
        
        if terminal:
            if multiple:
                script += "# Process each selected file\n"
                script += 'for file in "$@"; do\n'
                script += f'    {command} "$file"\n'
                script += 'done\n'
                script += 'read -p "Press Enter to continue..."\n'
            else:
                script += f'{command} "$1"\n'
                script += 'read -p "Press Enter to continue..."\n'
        else:
            if multiple:
                script += "# Process each selected file\n"
                script += 'for file in "$@"; do\n'
                script += f'    {command} "$file" &\n'
                script += 'done\n'
            else:
                script += f'{command} "$1" &\n'
        
        return script


class TestScriptGeneration(unittest.TestCase):
    """Test script generation logic"""
    
    def test_simple_script(self):
        """Test generating a simple script"""
        script = ScriptGenerator.generate_script("echo test", False, False)
        
        self.assertIn("#!/bin/bash", script)
        self.assertIn("echo test", script)
        self.assertIn('"$1"', script)
        self.assertNotIn("for file in", script)
        self.assertNotIn("read -p", script)
    
    def test_multiple_files_script(self):
        """Test generating script for multiple files"""
        script = ScriptGenerator.generate_script("process", True, False)
        
        self.assertIn("#!/bin/bash", script)
        self.assertIn("for file in", script)
        self.assertIn('process "$file"', script)
        self.assertIn('"$@"', script)
    
    def test_terminal_script(self):
        """Test generating script that runs in terminal"""
        script = ScriptGenerator.generate_script("cmd", False, True)
        
        self.assertIn("#!/bin/bash", script)
        self.assertIn("read -p", script)
        self.assertIn('cmd "$1"', script)
    
    def test_multiple_and_terminal(self):
        """Test generating script with both options"""
        script = ScriptGenerator.generate_script("cmd", True, True)
        
        self.assertIn("#!/bin/bash", script)
        self.assertIn("for file in", script)
        self.assertIn("read -p", script)
        self.assertIn('"$@"', script)
    
    def test_command_with_quotes(self):
        """Test commands containing quotes"""
        script = ScriptGenerator.generate_script("echo 'test'", False, False)
        self.assertIn("echo 'test'", script)
    
    def test_command_with_pipes(self):
        """Test commands with pipes"""
        script = ScriptGenerator.generate_script("cat | grep test", False, False)
        self.assertIn("cat | grep test", script)
    
    def test_empty_command(self):
        """Test with empty command"""
        script = ScriptGenerator.generate_script("", False, False)
        self.assertIn("#!/bin/bash", script)


class TestFileOperations(unittest.TestCase):
    """Test file operations"""
    
    def setUp(self):
        """Set up test environment"""
        self.test_dir = tempfile.mkdtemp()
        self.scripts_dir = Path(self.test_dir) / "scripts"
        self.scripts_dir.mkdir(parents=True, exist_ok=True)
    
    def tearDown(self):
        """Clean up test environment"""
        if os.path.exists(self.test_dir):
            shutil.rmtree(self.test_dir)
    
    def test_create_script_file(self):
        """Test creating a script file"""
        script_path = self.scripts_dir / "TestScript"
        script_content = ScriptGenerator.generate_script("echo hello", False, False)
        
        with open(script_path, 'w') as f:
            f.write(script_content)
        
        os.chmod(script_path, 0o755)
        
        # Verify file exists and is executable
        self.assertTrue(script_path.exists())
        self.assertTrue(os.access(script_path, os.X_OK))
        
        # Verify content
        with open(script_path, 'r') as f:
            content = f.read()
        self.assertIn("#!/bin/bash", content)
        self.assertIn("echo hello", content)
    
    def test_script_permissions(self):
        """Test that scripts have correct permissions"""
        script_path = self.scripts_dir / "PermTest"
        
        with open(script_path, 'w') as f:
            f.write("#!/bin/bash\necho test\n")
        
        os.chmod(script_path, 0o755)
        
        stat_info = os.stat(script_path)
        mode = stat_info.st_mode
        
        # Check owner can execute
        self.assertTrue(mode & 0o100)
    
    def test_readonly_directory(self):
        """Test creating script in read-only directory"""
        os.chmod(self.scripts_dir, 0o444)
        
        script_path = self.scripts_dir / "Test"
        
        with self.assertRaises(PermissionError):
            with open(script_path, 'w') as f:
                f.write("test")
        
        # Restore permissions for cleanup
        os.chmod(self.scripts_dir, 0o755)
    
    def test_special_characters_in_filename(self):
        """Test filenames with special characters"""
        test_names = [
            "Test Script",
            "Test-Script",
            "Test_Script",
            "Test.Script",
        ]
        
        for name in test_names:
            script_path = self.scripts_dir / name
            with open(script_path, 'w') as f:
                f.write("#!/bin/bash\necho test\n")
            
            self.assertTrue(script_path.exists())


class TestJSONOperations(unittest.TestCase):
    """Test JSON configuration operations"""
    
    def setUp(self):
        """Set up test environment"""
        self.test_dir = tempfile.mkdtemp()
        self.config_file = Path(self.test_dir) / "actions.json"
    
    def tearDown(self):
        """Clean up test environment"""
        if os.path.exists(self.test_dir):
            shutil.rmtree(self.test_dir)
    
    def test_save_and_load_actions(self):
        """Test saving and loading actions"""
        actions = {
            "Action1": {
                "description": "Test 1",
                "command": "cmd1",
                "filetypes": "all",
                "multiple": False,
                "terminal": False
            },
            "Action2": {
                "description": "Test 2",
                "command": "cmd2",
                "filetypes": "*.txt",
                "multiple": True,
                "terminal": True
            }
        }
        
        # Save
        with open(self.config_file, 'w') as f:
            json.dump(actions, f, indent=2)
        
        # Load
        with open(self.config_file, 'r') as f:
            loaded = json.load(f)
        
        self.assertEqual(loaded, actions)
    
    def test_load_corrupted_json(self):
        """Test loading corrupted JSON"""
        with open(self.config_file, 'w') as f:
            f.write("{ invalid json }")
        
        with self.assertRaises(json.JSONDecodeError):
            with open(self.config_file, 'r') as f:
                json.load(f)
    
    def test_empty_config(self):
        """Test loading empty config"""
        with open(self.config_file, 'w') as f:
            json.dump({}, f)
        
        with open(self.config_file, 'r') as f:
            loaded = json.load(f)
        
        self.assertEqual(loaded, {})


class TestFuzzInputs(unittest.TestCase):
    """Fuzz testing with various inputs"""
    
    def test_fuzz_commands(self):
        """Fuzz test with various commands"""
        test_commands = [
            "",  # Empty
            " ",  # Space
            "echo 'test'",
            "cat /etc/passwd",
            "echo test && echo test2",
            "echo test || echo test2",
            "echo test | grep e",
            "A" * 1000,  # Very long
            "echo 'test\nwith\nnewlines'",
            'echo "double\\"quotes"',
            "echo $USER",
            "echo `whoami`",
            "echo $(whoami)",
        ]
        
        passed = 0
        failed = 0
        
        for cmd in test_commands:
            try:
                script = ScriptGenerator.generate_script(cmd, False, False)
                self.assertIsInstance(script, str)
                self.assertIn("#!/bin/bash", script)
                passed += 1
            except Exception as e:
                failed += 1
                print(f"Failed with command {repr(cmd[:50])}: {e}")
        
        print(f"\nCommand fuzz test: {passed} passed, {failed} failed")
    
    def test_fuzz_script_generation(self):
        """Fuzz test script generation with random parameters"""
        test_cases = [
            ("echo test", False, False),
            ("echo test", True, False),
            ("echo test", False, True),
            ("echo test", True, True),
            ("", False, False),
            ("cmd with spaces", False, False),
            ("cmd | pipe", True, False),
            ("long " * 100, False, True),
        ]
        
        for cmd, multiple, terminal in test_cases:
            script = ScriptGenerator.generate_script(cmd, multiple, terminal)
            self.assertIn("#!/bin/bash", script)
            
            if multiple:
                self.assertIn("for file in", script)
            else:
                self.assertIn('"$1"', script)
            
            if terminal:
                self.assertIn("read -p", script)


class TestEdgeCases(unittest.TestCase):
    """Test edge cases and boundary conditions"""
    
    def setUp(self):
        self.test_dir = tempfile.mkdtemp()
        self.scripts_dir = Path(self.test_dir) / "scripts"
        self.scripts_dir.mkdir(parents=True, exist_ok=True)
    
    def tearDown(self):
        if os.path.exists(self.test_dir):
            shutil.rmtree(self.test_dir)
    
    def test_very_long_filename(self):
        """Test with very long filename"""
        # Most filesystems support 255 chars
        long_name = "A" * 200
        script_path = self.scripts_dir / long_name
        
        with open(script_path, 'w') as f:
            f.write("#!/bin/bash\necho test\n")
        
        self.assertTrue(script_path.exists())
    
    def test_unicode_in_script(self):
        """Test Unicode content in scripts"""
        script_content = "#!/bin/bash\n"
        script_content += "echo 'Testing: 你好 مرحبا こんにちは'\n"
        
        script_path = self.scripts_dir / "UnicodeTest"
        with open(script_path, 'w', encoding='utf-8') as f:
            f.write(script_content)
        
        with open(script_path, 'r', encoding='utf-8') as f:
            content = f.read()
        
        self.assertIn('你好', content)
    
    def test_multiple_scripts(self):
        """Test creating multiple scripts"""
        for i in range(50):
            script_path = self.scripts_dir / f"Script{i}"
            with open(script_path, 'w') as f:
                f.write(f"#!/bin/bash\necho {i}\n")
            os.chmod(script_path, 0o755)
        
        # Verify all were created
        scripts = list(self.scripts_dir.glob("Script*"))
        self.assertEqual(len(scripts), 50)
    
    def test_script_with_shebang_variations(self):
        """Test different shebang styles"""
        shebangs = [
            "#!/bin/bash",
            "#!/usr/bin/env bash",
            "#!/bin/sh",
        ]
        
        for i, shebang in enumerate(shebangs):
            script_path = self.scripts_dir / f"Shebang{i}"
            with open(script_path, 'w') as f:
                f.write(f"{shebang}\necho test\n")
            
            with open(script_path, 'r') as f:
                content = f.read()
            
            self.assertTrue(content.startswith("#!"))


class TestSecurityConcerns(unittest.TestCase):
    """Test for potential security issues"""
    
    def test_command_injection_resistance(self):
        """Test that dangerous commands are passed through as-is"""
        dangerous_commands = [
            "; rm -rf /",
            "$(malicious)",
            "`backdoor`",
            "&& evil_command",
            "|| evil_command",
        ]
        
        for cmd in dangerous_commands:
            script = ScriptGenerator.generate_script(cmd, False, False)
            # Script should contain the command but properly quoted
            self.assertIn("#!/bin/bash", script)
            # The script generator doesn't sanitize - that's intentional
            # It passes commands through to bash which handles them
    
    def test_path_traversal_in_filenames(self):
        """Test path traversal attempts in filenames"""
        test_dir = tempfile.mkdtemp()
        scripts_dir = Path(test_dir) / "scripts"
        scripts_dir.mkdir(parents=True, exist_ok=True)
        
        # These should be treated as literal filenames, not paths
        dangerous_names = [
            "../../../etc/passwd",
            "../../bad",
            "./test",
        ]
        
        for name in dangerous_names:
            # The Path / operator normalizes these
            script_path = scripts_dir / name
            # Check that the path is still within scripts_dir
            try:
                script_path.relative_to(scripts_dir)
                # If this succeeds, path is safe
                is_safe = True
            except ValueError:
                # Path escaped scripts_dir
                is_safe = False
            
            # We expect some to be unsafe (path traversal attempts)
            print(f"Path {name}: {'safe' if is_safe else 'UNSAFE'}")
        
        shutil.rmtree(test_dir)


def run_stress_tests():
    """Run stress tests with random data"""
    print("\n" + "=" * 70)
    print("STRESS TESTS")
    print("=" * 70 + "\n")
    
    test_dir = tempfile.mkdtemp()
    scripts_dir = Path(test_dir) / "scripts"
    scripts_dir.mkdir(parents=True, exist_ok=True)
    
    chars = string.ascii_letters + string.digits + " -_"
    
    success_count = 0
    fail_count = 0
    
    print("Creating 100 random scripts...")
    
    for i in range(100):
        name_len = random.randint(1, 50)
        cmd_len = random.randint(1, 100)
        
        name = ''.join(random.choice(chars) for _ in range(name_len))
        cmd = ''.join(random.choice(chars) for _ in range(cmd_len))
        
        try:
            script_content = ScriptGenerator.generate_script(cmd, 
                                                            random.choice([True, False]),
                                                            random.choice([True, False]))
            script_path = scripts_dir / name.strip()
            
            if script_path.name:  # Only if name isn't empty after strip
                with open(script_path, 'w') as f:
                    f.write(script_content)
                os.chmod(script_path, 0o755)
                success_count += 1
        except Exception as e:
            fail_count += 1
            if fail_count <= 5:
                print(f"  Failure: {str(e)[:60]}")
    
    print(f"\nResults: {success_count} succeeded, {fail_count} failed")
    print(f"Success rate: {(success_count / 100 * 100):.1f}%")
    
    shutil.rmtree(test_dir)


def print_summary(result):
    """Print test summary"""
    print("\n" + "=" * 70)
    print("TEST SUMMARY")
    print("=" * 70)
    print(f"Tests run: {result.testsRun}")
    print(f"Successes: {result.testsRun - len(result.failures) - len(result.errors)}")
    print(f"Failures: {len(result.failures)}")
    print(f"Errors: {len(result.errors)}")
    
    if result.testsRun > 0:
        success_rate = (result.testsRun - len(result.failures) - len(result.errors)) / result.testsRun * 100
        print(f"Success rate: {success_rate:.1f}%")
    
    print("=" * 70)
    
    if result.failures:
        print("\nFAILURES:")
        for test, traceback in result.failures:
            print(f"\n{test}:")
            print(traceback)
    
    if result.errors:
        print("\nERRORS:")
        for test, traceback in result.errors:
            print(f"\n{test}:")
            print(traceback)


if __name__ == "__main__":
    print("=" * 70)
    print("CAJA CONTEXT MENU MANAGER - COMPREHENSIVE TEST SUITE")
    print("Testing core logic without GUI dependencies")
    print("=" * 70)
    print()
    
    # Create test suite
    loader = unittest.TestLoader()
    suite = unittest.TestSuite()
    
    # Add all test classes
    suite.addTests(loader.loadTestsFromTestCase(TestScriptGeneration))
    suite.addTests(loader.loadTestsFromTestCase(TestFileOperations))
    suite.addTests(loader.loadTestsFromTestCase(TestJSONOperations))
    suite.addTests(loader.loadTestsFromTestCase(TestFuzzInputs))
    suite.addTests(loader.loadTestsFromTestCase(TestEdgeCases))
    suite.addTests(loader.loadTestsFromTestCase(TestSecurityConcerns))
    
    # Run tests
    runner = unittest.TextTestRunner(verbosity=2)
    result = runner.run(suite)
    
    # Run stress tests
    run_stress_tests()
    
    # Print summary
    print_summary(result)
    
    # Exit with appropriate code
    exit(0 if result.wasSuccessful() else 1)
